import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import './globals.css'

import Header from '@/components/header/header'
import Footer from '@/components/footer'
import Image from 'next/image'

import bgPattern from '@/public/assets/pattern.jpg'
import bgPatternMobile from '@/public/assets/pattern-mobile.jpg'
import ScrollToTop from '@/components/scroll-to-top'
import LenisProvider from '@/components/lenis-provider'

import { getGlobalData, getHomeData } from '@/lib/queries'

const jostSansSerif = Jost({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
	variable: '--font-jost',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Elements Hotel template',
	description: 'Generated by create next app',
}

const RootLayout = async ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {

	const global = await getGlobalData();

	const home = await getHomeData(['meta_title','meta_description']);






	return (
		<html lang='pl'>
			<body className={`${jostSansSerif.variable}  antialiased relative`}>
				<LenisProvider>
					<Image
						src={bgPattern}
						alt='bg'
						className='hidden md:block absolute top-0 left-0 w-full h-full object-cover -z-10 bg-repeat'
						fill
						quality={100}
						priority
						sizes='(max-width: 768px) 0px, 100vw'
					/>
					<Image
						src={bgPatternMobile}
						alt='bg'
						className=' md:hidden absolute top-0 left-0 w-full h-full object-cover -z-10 bg-repeat'
						fill
						quality={100}
						priority
						sizes='(max-width: 768px) 100vw, 0px'
					/>
					<Header global={global} />
					{children}
					<Footer global={global} />
					<ScrollToTop />
				</LenisProvider>
			</body>
		</html>
	)
}

export default RootLayout
